# Stage 1: Build React application
FROM node:14.17.0-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Serve React application with Nginx
FROM nginx:alpine

# Copy built app from Stage 1
COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration file to handle React routing
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
